### ISSUE TITLE
Mismatched type in date spine macro

### ISSUE THREAD

**Issue by joshtemple** [fishtown-analytics/dbt-utils#102]
#101 seems to have broken the date_spine macro for datepart `day`. I'm running the macro with the following syntax:
```
{{
  dbt_utils.date_spine(
    datepart="day",
    start_date="'2010-01-01'",
    end_date="date_add(current_date(), interval 3 month)")
}}
```

When I run the macro, I get this error in BigQuery: ```No matching signature for operator <= for argument types: DATETIME, DATE. Supported signatures: ANY <= ANY at [142:11]```

The offending SQL is here:

```
select (
    datetime_add(
        cast( '2010-01-01' as datetime),
    interval row_number() over (order by 1) - 1 day
    )
) as date_day
...
select *
from all_periods
where date_day <= date_add(current_date(), interval 3 month)
```

I believe that `date_day` used to be of type `date` instead of `datetime`, which is causing the error with the comparison. It seems this change was introduced by #101 to `macros/cross_db_utils/dateadd.sql`.

**Comment by joshtemple** [comment]
A related thought that I would be happy to move to a new issue: this repo is big enough and widely used enough that it should probably maintain versioned release branches so that potentially breaking changes like this aren't automatically introduced by running `dbt deps`.

The `revision` option in dbt's `packages.yml` ([here](https://docs.getdbt.com/docs/package-management)) isn't as useful unless there's a distinct branch for each version that I can lock in to or update to.

**Comment by drewbanin** [comment]
hey @joshtemple - thanks for opening this issue. We actually made this change to bring the `dateadd` macro in line with the other implementations of `dateadd` for snowflake/redshift. This is deeply distressing to me, but `date_add` on BigQuery doesn't work with sub-day time parts (like hour/min/sec). The corresponding `timestamp_add` doesn't work with super-day parts (like week, month, year). So, `datetime_add` is the only function that will actually accept all of the different time parts that the rest of this package's date macros support.

I _really_ didn't want to use `datetime` here, but I unfortunately didn't see a good way around it. If you have other ideas for how this could work, I'd be super interested in hearing them! If you're cool with datetimes, i'd recommend casting the column returned by `dateadd` to a `date` to suit your needs.

To your last point, we cut releases that are (mostly) semantically versioned. You can supply a tag name in the `revision` part of your `packages.yml` specs to pin your dep to a specific version. I highly recommend doing that for _all_ of your dependencies. You can find the list of tags here: https://github.com/fishtown-analytics/dbt-utils/releases

**Comment by joshtemple** [comment]
Makes perfect sense, I'm totally fine with using `datetime` in this instance. Thanks for the heads up on the release tags, that's exactly what I was looking for! I figured you had already thought of this and I was just missing something...

Going to go ahead and close this issue.
