### ISSUE TITLE
Use `getdate()` instead of `current_timestamp` on Redshift impl of current_timestamp() macro

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt-utils#109]
Existing code: https://github.com/fishtown-analytics/dbt-utils/blob/28bdf56915765f1ea9ab3e38584e3cb38992a700/macros/cross_db_utils/current_timestamp.sql#L5

The `current_timestamp` value on Redshift looks deprecated ([via the docs]( https://docs.amazonaws.cn/en_us/redshift/latest/dg/Date_functions_header.html)). There have also been reports of `current_timestamp` returning the wrong time.

**Comment by tjengel** [comment]
I'm trying to push a branch for this, but getting an error when trying to push to the repo
```
ERROR: Permission to fishtown-analytics/dbt-utils.git denied to tjengel.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Do I need to get access to push to this repo? Thanks

**Comment by drewbanin** [comment]
hey @tjengel - you'll want to fork this repo into your own GitHub account (or an Organization that you're a member of). After that, you should be able to push your changes to a branch on your fork, then open up a PR from your forked repo into the dbt-utils repo. Let me know if there's anything I can help out with here

**Comment by tjengel** [comment]
How do I get hooked up with the integration-tests profile so I can run the tests locally?

**Comment by tjengel** [comment]
@drewbanin This should be ready for a CI build.

**Comment by tjengel** [comment]
@drewbanin I think we can close this issue.

**Comment by drewbanin** [comment]
ah, thanks @tjengel!
