### ISSUE TITLE
get_column_values returns an error if passed a `ref`, but the model has not been previously built

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/dbt-utils#119]
## Steps to reproduce
1. Call `get_column_values` with a `ref` passed to it:
```
-- survey_guest_facts.sql
{% set slug_list = dbt_utils.get_column_values(table=ref('survey_responses'), column='slug') %}
...
```
2. Ensure the upstream model has not yet been built 
3. Run `dbt compile`

## Expected results
An empty list is returned during compilation, with no error

## Actual results
A database error occurs:
```
$ dbt compile
Found 95 models, 251 tests, 0 archives, 1 analyses, 236 macros, 7 operations, 1 seed files

13:49:01 | Concurrency: 1 threads (target='dev2')
13:49:01 |
Encountered an error:
Runtime Error
  Database Error in model survey_guest_facts (models/components/survey_guest_facts.sql)
    relation "cc_base.survey_responses" does not exist
```
From the logs:
```
2019-02-11 13:50:08,257 (Thread-1): Compiling model.jaffle_shop.survey_guest_facts
2019-02-11 13:50:08,272 (Thread-1): Acquiring new redshift connection "survey_guest_facts".
2019-02-11 13:50:08,272 (Thread-1): Re-using an available connection from the pool.
2019-02-11 13:50:08,272 (Thread-1): Using redshift connection "survey_guest_facts".
2019-02-11 13:50:08,272 (Thread-1): On survey_guest_facts: BEGIN
2019-02-11 13:50:08,298 (Thread-1): SQL status: BEGIN in 0.03 seconds
2019-02-11 13:50:08,299 (Thread-1): Using redshift connection "survey_guest_facts".
2019-02-11 13:50:08,299 (Thread-1): On survey_guest_facts: 

        select
            slug as value

        from "cc_base"."survey_responses"
        group by 1
        order by count(*) desc

        
2019-02-11 13:50:08,382 (Thread-1): Postgres error: relation "cc_base.survey_responses" does not exist

2019-02-11 13:50:08,382 (Thread-1): On survey_guest_facts: ROLLBACK
```

## System info
```
$ dbt debug
dbt version: 0.12.2
python version: 3.7.2
python path: /usr/local/Cellar/dbt/0.12.2/libexec/bin/python3.7
```
version of utils: 0.1.20

## Notes
- I'm interested in why this fails on `compile` but not on `run`.
- I haven't thought too hard about the solution to this, so not sure if it's an easy fix or not

**Comment by drewbanin** [comment]
dbt should build these models in the correct order because of the `ref` statement provided in the call to `get_column_values`:

```
dbt_utils.get_column_values(table=ref('survey_responses'), column='slug')
```

So, during a run, `survey_responses` will be built before `survey_guest_facts` in the example above. When dbt gets to running `survey_guest_facts`, the `survey_responses` table will exist and this macro will execute successfully.

During compilation, dbt actually executes the statement in `survey_guest_facts`, but `survey_responses` doesn't exist yet. Maybe the solution is to return an empty list of the destination Relation doesn't actually exist?

**Comment by emilieschario** [comment]
> Maybe the solution is to return an empty list of the destination Relation doesn't actually exist?

Yes! I think the macro should return an empty string if its not an execute (run). I'm not clear how https://github.com/fishtown-analytics/dbt-utils/pull/133 might affect this.

**Comment by emilieschario** [comment]
## Problem Statement
The `get_column_values` [macro](https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/sql/get_column_values.sql) fetches the unique values for `column` in the table `table`.

There are four circumstances for how this is run:
* when compiling on a fresh schema (e.g. schema doesn't exist)
* when compiling on an existing schema (e.g. schema does exist)
* when running a full run 
* when running a the specific model

In both of these run circumstances, sometimes the referenced model can exist and sometimes it can't. 

There are three ways to handle this:
* Option 1- Users handle this in their own projects
* Option 2- dbt utils decides on the way to handle this 
* Option 3- dbt utils has a default that users can configure

## Currently
If the model referenced in the ref statement doesn't exist, the compile or run the specific model fails. It errors out saying that the schema (of the ref'd model) doesn't exist. (Also, not a great error message.)

## Proposal
* During a `compile`, it should not fail; if the model doesn't exist already, it should produce an empty list. 
* During a `run`, it should fail; if the model doesn't exist already it should fail with a better error message indicating the model doesn't exist. 
* These default behaviors should be customizable each time the macro is used.

**Comment by drewbanin** [comment]
Thanks for this comprehensive writeup @emilieschario!

It's unfortunately going to be challenging for dbt to differentiate between things that happen in `dbt compile` and `dbt run`. In both cases, dbt "runs", but it does so with either the [CompileRunner](https://github.com/fishtown-analytics/dbt/blob/dev/wilt-chamberlain/core/dbt/node_runners.py#L286) or the [ModelRunner](https://github.com/fishtown-analytics/dbt/blob/dev/wilt-chamberlain/core/dbt/node_runners.py#L300).

What do you think about this approach:
1. Add an optional argument, `default`, with the default value `none`
2. In the macro, check if the target `table` Relation exists using `adapter.get_relation()`
3. If the table exists, then proceed as normal
4. If the table does not exist and `default` is not `none`, then return `default`
5. If the table does not exists and no `default` is provided, then raise an exception

This gives control to the end-user while avoiding a situation where the macro does something a user wouldn't expect it to do. Curious to hear your thoughts!
