### ISSUE TITLE
relation_alias parameter in the "star" macro

### ISSUE THREAD

**Issue by broom9** [fishtown-analytics/dbt-utils#130]
Is it inserting the prefix at the right place? When writing a model like:
```
SELECT 
{{ dbt_utils.star(from=ref('r_group'), relation_alias='group') }}
FROM {{ ref('r_group') }}
```

I'm seeing compiled SQL like 
```
SELECT 
         group. 
  "COMPANY_ID"
```
while I was expecting:
```
SELECT  
  "COMPANY_ID" as "GROUP_COMPANY_ID"
```

Is this how the relation_alias parameter supposed to work?

**Comment by drewbanin** [comment]
Hey @broom9 - The `relation_alias` field is used to specify the table to select from! Here's an example use case:

```
select 
  {{ dbt_utils.star(from=ref('r_group'), relation_alias='group', except=['name']) }},
  {{ dbt_utils.star(from=ref('r_user'), relation_alias='user', except=['name']) }}
FROM {{ ref('r_group') }} as group
join {{ ref('r_user') }} as user on group.id = user.group_id
```

We don't really find ourselves writing code like this, and I think it's generally a better practice to separate these select statements out:

```sql
with groups as (

  select
    {{ dbt_utils.star(from=ref('r_group'), relation_alias='group', except=['name']) }}
  from {{ ref('r_group') }}

),

users as (

  select
    {{ dbt_utils.star(from=ref('r_user'), relation_alias='group', except=['name']) }}
  from {{ ref('r_group') }}

)

select *
from users
join groups on group.id = user.group_id
```

I think an approach like this obviates the need for the `relation_alias` parameter. Going to close this, but let me know if you have any questions :)
