### ISSUE TITLE
Broken 0.10 compatibility from MR133

### ISSUE THREAD

**Issue by freyley** [fishtown-analytics/dbt-utils#134]
[MR 133](https://github.com/fishtown-analytics/dbt-utils/pull/133) seems to have broken compatibility with DBT 0.10.x.

Specifically:
```
Compilation Error in None unknown (cross_db_utils/_is_relation.sql)
  Encountered unknown tag 'do'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
    line 3
```
Specifically [here](https://github.com/fishtown-analytics/dbt-utils/pull/133/files#diff-856c12bf61403b4749cced14f05801f9R2)
```
{%- do exceptions.raise_compiler_error("Macro " ~ macro ~ " expected a Relation but received the value: " ~ obj) -%}
```

**Comment by freyley** [comment]
Is there a way to specify a commit hash in this, or should I fork the repo and point at the fork?

repositories:
    - https://github.com/fishtown-analytics/dbt-utils.git

**Comment by drewbanin** [comment]
hey! Yes - you should definitely _always_ point a `dbt deps` package to a specific version. dbt v0.10.0 is pretty old at this point, I'd have to check on what the syntax is for the old `repositories:` list. I think it was:

```
repositories:
- https://github.com/fishtown-analytics/dbt-utils.git@0.1.22
```

Via the [releases](https://github.com/fishtown-analytics/dbt-utils/releases) for the package.

In newer versions of dbt, you can use a `packages.yml` file instead: https://docs.getdbt.com/docs/package-management#section-specifying-package-versions
