### ISSUE TITLE
[Issue] get_column_values now only accepts a relation

### ISSUE THREAD

**Issue by clrcrl** [fishtown-analytics/dbt-utils#153]
## Steps to reproduce
1. Install dbt-utils v0.2.1
2. Call `get_column_values` with a string table reference
```
{{ dbt_utils.get_column_values(
    table="raw_jaffle_shop.customers",
    column='first_name',
    max_records=50
) }}
```
## Expected results
* Macro compiles correctly (this was the behaviour <0.2.1)

## Actual results
```
Running with dbt=0.14.0
Found 10 models, 28 tests, 0 snapshots, 0 analyses, 249 macros, 0 operations, 0 seed files, 3 sources

16:53:00 | Concurrency: 1 threads (target='dev')
16:53:00 |
Encountered an error:
Runtime Error
  Compilation Error in macro get_column_values (macros/sql/get_column_values.sql)
    'str object' has no attribute 'database'
```

## Commentary
Prior to v0.2.1, you could pass `get_column_values` a table like this `my_schema.my_table`.

However #152 now means you need to pass the macro a `relation` instead. All of these are valid:
```
{{ dbt_utils.get_column_values(
    table=ref('stg_jaffle_shop__customers'),
    column='first_name',
    max_records=50
) }}
```
```
{{ dbt_utils.get_column_values(
    table=source('raw_jaffle_shop', 'customers'),
    column='first_name',
    max_records=50
) }}
```
```
{%- set source_relation = adapter.get_relation(
      database=target.database,
      schema='raw_jaffle_shop',
      identifier="customers") -%}

{{ dbt_utils.get_column_values(
    table=source_relation,
    column='first_name',
    max_records=50
) }}

```

I'm totally 100% behind this change, but there needs to be some cleaning up here to communicate it.
- [ ] The README.md still says shows an example of passing a hardcoded table reference in the [pivot example](https://github.com/fishtown-analytics/dbt-utils/blob/master/README.md#pivot-source)
- [ ] Techhhhhnically we should replace the `table` argument name with `relation`, but that's likely going to break things (on the fence about whether we should fix it)
- [ ] There's also a little bit of redundant code in `get_column_values` which would be good to clean up:

```
    {%- set target_relation = adapter.get_relation(database=table.database,
                                          schema=table.schema,
                                         identifier=table.identifier) -%}
```
can be replaced with
```
    {%- set target_relation = table -%}
```

**Comment by clrcrl** [comment]
@emilieschario – I'm happy to fix this, but also happy for you to take this one :)

**Comment by emilieschario** [comment]
Thanks so much for taking this @clrcrl! I was traveling this weekend!
