### ISSUE TITLE
config-version change breaks package on DBT 0.16.0

### ISSUE THREAD

**Issue by Matt343** [fishtown-analytics/dbt-utils#237]
When installing the package with no max version specified, the `dbt run` command will fail:
```Runtime Error
  Failed to read package at /usr/src/app/dbt_modules/dbt_utils: Runtime Error
    at path []: Additional properties are not allowed ('config-version' was unexpected)", "exc_info": "jsonschema.exceptions.ValidationError: Additional properties are not allowed ('config-version' was unexpected)

Failed validating 'additionalProperties' in schema:
    {'$schema':...```

This seems to be a problem with the `dbt deps` command, which shouldn't be installing the newest version anyway since it requires a dbt version higher than what is running. I'm wondering if this is related to bringing in `dbt-utils` as a transitive dependency instead of an explicit one?

**Comment by clrcrl** [comment]
Hi Matt — can you please share your `packages.yml`? 

We just created [a release with a breaking change](https://github.com/fishtown-analytics/dbt-utils/releases). You should always pin your version number to avoid any breaking changes

**Comment by Matt343** [comment]
Before the change, my packages.yml looked like this:
```packages:
  - package: fishtown-analytics/logging
    version: 0.2.2
```
Pinning the transitive dependency fixed the issue, but it seems like DBT shouldn't be trying to install that version anyway since the required dbt version isn't satisfied.

**Comment by clrcrl** [comment]
Ah, got it. 

We _should_ have had an upper limit on the `logging` package — I'm going to do a patch release shortly [here](https://github.com/fishtown-analytics/dbt-event-logging/pull/27)

**Comment by Matt343** [comment]
Awesome, thanks. It just caught me by surprise when things started failing, trying to keep others from ending up confused. I'll close this since it seems like the fix is elsewhere

**Comment by clrcrl** [comment]
If you update to `version: 0.2.3`, things should work now!
