### ISSUE TITLE
Declaring an aggregate function leads to an error

### ISSUE THREAD

**Issue by rbval** [fishtown-analytics/dbt-utils#239]
Running `dbt run` when declaring the following aggregate function:
```
create aggregate mul(float) ( sfunc = float8mul, stype=float )
```
leads to the following error:
```
  syntax error at or near "create"
  LINE 4:     create aggregate mul(float) ( sfunc = float8mul, stype=f...
```
What's a way to create my own aggregate function in dbt? Postgres doesn't have `mul` ootb and I need it.

**Comment by clrcrl** [comment]
Hi @rbval — dbt runs the SQL against your warehouse. So the question should be:
> What's a way to create my own aggregate function in Postgres?
(Which I don't know the answer to!)
Once you have that figured out, you can version control this code in your dbt project — check out [this related discourse post](https://discourse.getdbt.com/t/using-dbt-to-manage-user-defined-functions/18).

Hope that helps! For now I'm closing off this issue as it's not related to dbt-utils
