### ISSUE TITLE
Installing dbt-utils 0.4.0 fails due to "Additional properties are not allowed ('config-version' was unexpected)" error

### ISSUE THREAD

**Issue by sindarknave** [fishtown-analytics/dbt-utils#240]
### Describe the bug
Installing dbt 0.4.0 fails due to "Additional properties are not allowed ('config-version' was unexpected)" error

### Steps to reproduce
In packages.yml:
```
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.4.0
```

Running `dbt deps`, we get a runtine error and:

```
Installing fishtown-analytics/dbt_utils@0.4.0
Runtime Error
  Failed to read package at /usr/src/develop/user-6374/environment-7233/repository-6161/dbt_modules/dbt_utils: Runtime Error
    at path []: Additional properties are not allowed ('config-version' was unexpected) Code: 10007
```

### Expected results
Installing version 0.3.0 seems to succeed:

```
Installing fishtown-analytics/dbt_utils@0.3.0
  Installed from version 0.3.0
```

In my `dbt_project.yml`: 

```
name: 'xxx_project'
version: '1.0.0'
```

**Comment by clrcrl** [comment]
Which version of dbt are you using? You can check with `dbt --version`

**Comment by sindarknave** [comment]
hey, i'm on `0.16.1`

**Comment by clrcrl** [comment]
Cool, so as we wrote in the [release notes](https://github.com/fishtown-analytics/dbt-utils/releases), this version is compatible with dbt v0.17.0 only.

You should use the previous release (`0.3.0`) until you're ready to upgrade your dbt version.
