### ISSUE TITLE
Make sample date_spine code cross-db friendly

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/dbt-utils#301]
Right now, the [sample readme code](https://github.com/fishtown-analytics/dbt-utils#date_spine-source) for `date_spine` does not work on databases (i.e. BigQuery) that lack `to_date` or have different implementations of `dateadd`:
```sql
{{ dbt_utils.date_spine(
    datepart="minute",
    start_date="to_date('01/01/2016', 'mm/dd/yyyy')",
    end_date="dateadd(week, 1, current_date)"
   )
}}
```

While it's nice to indicate that users can pass SQL expressions to the macro arguments, I think it's more important that first-time users can have working code right away.

I propose changing the readme example to:
```sql
{{ dbt_utils.date_spine(
    datepart="day",
    start_date="cast('2019-01-01' as date)",
    end_date="cast('2020-01-01' as date)"
   )
}}
```
I'd be happy to open a PR for this, it's a really minor change

**Comment by clrcrl** [comment]
Yep would love for you to change this :)
