### ISSUE TITLE
'dispatch'-ize the schema test matcros

### ISSUE THREAD

**Issue by swanderz** [fishtown-analytics/dbt-utils#311]
### Describe the bug
per [this discussion](https://github.com/dbt-msft/tsql-utils/pull/6#discussion_r547601190) with @jtcohen6, we'll need make the schema test macros make use of `adapter.dispatch()` so that `tsql-utils` can customize the schema tests.

### Are you interested in contributing the fix?

Yep, but might not get to it for a few weeks due to holidays & PTO

**Comment by jtcohen6** [comment]
Ultimately, I think we should add `dispatch` to every macro in the package (:

**Comment by swanderz** [comment]
#312 closes this out!
