### ISSUE TITLE
Increase threads for Integration Test suite

### ISSUE THREAD

**Issue by clausherther** [fishtown-analytics/dbt-utils#315]
### Describe the feature
Currently integration tests run on 1 thread; this causes the integration test models and schema tests to run very slowly, particularly on Snowflake and BigQuery where a higher thread count would speed things up (and potentially save $ on Snowflake compute). 
See:

![image](https://user-images.githubusercontent.com/7342749/103056404-1bc1f000-455a-11eb-8a91-545884521249.png)

I propose increasing the `threads` to 4 or even higher, e.g. 8, for Snowflake and BigQuery integration tests.

### Who will this benefit?
Anyone submitting PRs and the FA team if this ends up saving Snowflake compute cost.

### Are you interested in contributing this feature?
Yes

**Comment by clrcrl** [comment]
@jtcohen6 — as guardian of the testing warehouses, do you foresee any issues with this? I think it sounds great! I'd also love to figure out if we can have the different warehouse test jobs running in parallel too, which would considerably speed things up :)

**Comment by jtcohen6** [comment]
> do you foresee any issues with this?

nope!

> I'd also love to figure out if we can have the different warehouse test jobs running in parallel too, which would considerably speed things up :)

agreed—this is possible by switching the CircleCI config to use `workflows` instead of `jobs`. I could open a PR for that (:
