### ISSUE TITLE
error in calling noop_statement

### ISSUE THREAD

**Issue by shnaqawi** [fishtown-analytics/dbt-utils#337]
https://github.com/fishtown-analytics/dbt-utils/blob/bbba960726667abc66b42624f0d36bbb62c37593/macros/materializations/insert_by_period_materialization.sql#L182

![image](https://user-images.githubusercontent.com/32584341/108435314-2e356e80-7217-11eb-9bbf-355c53e14f96.png)
I'm got this error today. the pipeline was working fine just before this. Any ideas?

**Comment by clrcrl** [comment]
Can you share the contents of your `packages.yml` file? (I think the template would have asked for this — we put those templates in for a reason, please use them in the future!)

**Comment by shnaqawi** [comment]
> Can you share the contents of your `packages.yml` file? (I believe that the [bug report template](https://github.com/fishtown-analytics/dbt-utils/issues/new?assignees=&labels=bug%2C+triage&template=bug_report.md&title=) asks for this — we put those templates in for a reason, please use them in the future.)

I guess I just referenced the line in a new comment. Will do a bug report next time. 

The issues was caused by upgrading to the new DBT version and our materialization code wasn't updated. It's resolved now, so I'm closing this thread. thanks!
