### ISSUE TITLE
generate_series returning error when upper bound too large

### ISSUE THREAD

**Issue by dwallace0723** [fishtown-analytics/dbt-utils#39]
The `generate_series` macro returns an error when your `upper_bound` config option is too large. When set to 100k, the returned error is:

```
Encountered an error:
range too big, maximum size for range is 100000
```

The macro seems to work fine with `upper_bound` set to any positive number < 100k. I imagine this is a jinja `range()` limitation.

**Comment by drewbanin** [comment]
cc @jthandy :)

**Comment by jthandy** [comment]
resolved by https://github.com/fishtown-analytics/dbt-utils/pull/40.

thanks for the heads up :)
