### ISSUE TITLE
Make `date_spine` work with Snowflake

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt-utils#47]
Issue with [row_number()](https://github.com/fishtown-analytics/dbt-utils/blob/master/macros/datetime/date_spine.sql#L50)

Window function type [ROW_NUMBER] requires ORDER BY in window specification.

**Comment by jthandy** [comment]
@drewbanin this is closed, yes?

https://github.com/fishtown-analytics/dbt-utils/pull/48

**Comment by drewbanin** [comment]
@jthandy yessir
