### ISSUE TITLE
Version out of date

### ISSUE THREAD

**Issue by mplovepop** [fishtown-analytics/dbt-utils#78]
Version in `dbt_project.yml` is 0.1.0 but latest git tag is 0.1.15

**Comment by tjengel** [comment]
@drewbanin Should this issue be closed?

**Comment by drewbanin** [comment]
@tjengel yep! I didn't realize we had an issue for this.

We should enforce that the `version:` in `dbt_project.yml` matches the version number in a given release, but we don't have a good mechanism to do that at the moment! This `version` field is unused and I think unavailable in the dbt context, so there's limited merit to keeping it in sync for the moment.
